export const SET_LISTINGS = "SET_LISTINGS";
export const SET_CART_ITEMS = "SET_CART_ITEMS";
export const ADD_NEW_LISTING = "ADD_NEW_LISTING";
export const SET_MY_LISTINGS = "SET_MY_LISTINGS";
export const SET_LIKED_LISTINGS = "SET_LIKED_LISTINGS";
export const UPDATE_MY_LISTINGS = "UPDATE_MY_LISTINGS";